### ISSUE TITLE
Error when starting.

### ISSUE THREAD

**Issue by Tiebe** [DaRealBerlm/SaveTheWorldDailyRewards#1]
```
win86>SaveTheWorldRewards.exe
File does not exist, claiming reward...
Unhandled exception. OpenQA.Selenium.DriverServiceNotFoundException: The chromedriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html.
   at OpenQA.Selenium.DriverService.FindDriverServiceExecutable(String executableName, Uri downloadUrl)
   at OpenQA.Selenium.Chrome.ChromeDriverService.CreateDefaultService()
   at SaveTheWorldRewards.WebdriverManager.GetAuthCode()
   at SaveTheWorldRewards.Program.Main()
   at SaveTheWorldRewards.Program.<Main>()
```

 I can't start the program. I have the chromedriver.exe file in the same directory, so what would be wrong?

**Comment by DhrumanGupta** [comment]
Hey! 
Thanks for trying this out.
The issue here is that you do _not_ have chromedriver.exe in the PATH. From what you said, I believe you have it with the executable.

Try adding chromedriver to a path variable. You can learn how to do that here:
https://www.youtube.com/watch?v=dz59GsdvUF8&ab_channel=ArturSpirin

Let me know if you face any issues

**Comment by Tiebe** [comment]
Hey, that worked, I have a new problem now:


```
win64>SaveTheWorldRewards.exe
File does not exist, claiming reward...
OpenQA.Selenium.WebDriverException: unknown error: cannot create default profile directory
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options)
   at SaveTheWorldRewards.WebdriverManager.GetAuthCode()
Please close your chrome window.
Please provide a valid token!

```

I think it might be because I have Chrome version 89.0.4389.90, while the latest version chromedriver currently supports is 89.0.4389.23. Any solution for this one?

**Comment by DhrumanGupta** [comment]
Alright, I found the issue here. I am so sorry, overlooked that part. I just updated the repository and released a new version. Check it out, it should work properly now.

**Comment by Tiebe** [comment]
It works now, awesome! Thank you so much, it would be great if I would be able to run this on a Raspberry Pi one day, but thats for a later date. :) Btw, you should mention to run `pip install requests`, because it's not preinstalled with Python. Thank you!

**Comment by DhrumanGupta** [comment]
Thanks a lot for that! I'll make a requirements.txt file for this.
Also, for portability, I had a question:
Would you, as a user, prefer Dotnet core to be a requirement? As of now, the files are self-contained, so there are no .net dependencies. Let me know what you would prefer

**Comment by Tiebe** [comment]
I wouldn't really mind, because I have .net installed on my computer anyway, but for a normal user, I think it would be best if everything would be self-contained!

**Comment by Tiebe** [comment]
After looking into things (and trying some stuff out with your code myself), it might be better to use .net core anyway, since a lot of other programs also have it as a dependency, so the user would already have it installed. In the end, it's whatever you prefer of course!
